### ISSUE TITLE
WordNet for Android

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#103]
Instruction for RiWordNet on Processing (Android):

1.Download and unzip [RiWordNet 3.1 Database file](http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz) on Android
2.Create and save the sketch named 'RiWordNet' as follow
```processing
importa rita.*;

RiWordNet wordnet = new RiWordNet("wn3.1.dict/dict");
```
3.Put the database folder to storage/sdcard0/Sketchbook/RiWordNet/data
4.Run the sketch 

error encountered:
```
Initializing build sequence...
Deleted old build folder
Injected log broadcaster
Detected architecture armeabi-v7a

Packaging resources with AAPT...
Compiling with ECJ...
----------
1. ERROR in /data/data/com.calsignlabs.apde/app_build/src/processing/test/riwordnet/RiWordNet.java (at line 26)
RiWordNet wordnet = new RiWordNet("wn3.1.dict/dict");
                    ^^^^^^^^^^^^^^^^^^^^^^^
The constructor RiWordNet(String) is undefined
----------
1 problem (1 error)
Compilation with ECJ failed
```

**Comment by dhowe** [comment]
Are you sure you are using a current version of RiTa here? That is most certainly a valid constructor. From the source:

![screen shot 2015-05-13 at 3 30 48 am](https://cloud.githubusercontent.com/assets/737638/7596487/98e6e2fc-f920-11e4-88bf-6d0ed54b6021.png)

**Comment by CyrusSUEN** [comment]
> Are you sure you are using a current version of RiTa here?

Yes



> Or is the problem that you named your test sketch with the same name as the class you are testing (RiWordNet.java)?

And you are correct after renaming the sketch I can run it without the above error but a new one
```
Initializing build sequence...
Deleted old build folder
Injected log broadcaster
Detected architecture armeabi-v7a

Packaging resources with AAPT...
Compiling with ECJ...

Dexing with DX Dexer...
Merging DEX files with DX Merger...
Merged dex A (5 defs/4.2KiB) with dex B (151 defs/645.6KiB). Result is 156 defs/765.3KiB. Took 1.6s
Merged dex A (156 defs/765.3KiB) with dex B (2 defs/1.1KiB). Result is 158 defs/914.6KiB. Took 1.7s
Merged dex A (158 defs/914.6KiB) with dex B (13 defs/152.3KiB). Result is 171 defs/1299.4KiB. Took 2.1s
Merged dex A (171 defs/1299.4KiB) with dex B (270 defs/488.0KiB). Result is 441 defs/2209.4KiB. Took 3.1s
Result compacted from 3084.6KiB to 1449.1KiB to save 1635.5KiB
Merged dex A (441 defs/2209.4KiB) with dex B (201 defs/212.6KiB). Result is 642 defs/1449.1KiB. Took 6.6s
Building APK file with APKBuilder...

Signing and Zipaligning with ZipSigner...
Installing APK file...









java.lang.ExceptionInInitializerError
at rita.RiWordNet.<init>(RiWordNet.java:111)
at rita.RiWordNet.<init>(RiWordNet.java:81)
at processing.test.sketch2.sketch2.setup(sketch2.java:26)
at processing.core.PApplet.handleDraw(Unknown Source)
at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
at processing.core.PApplet.run(Unknown Source)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.util.MissingResourceException: Can't find resource for bundle 'JWNLResource_en', key ''
at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
at rita.wordnet.jwnl.util.ResourceBundleSet.getBndl(ResourceBundleSet.java:75)
at rita.wordnet.jwnl.util.ResourceBundleSet.access$100(ResourceBundleSet.java:13)
at rita.wordnet.jwnl.util.ResourceBundleSet$1.hasMoreElements(ResourceBundleSet.java:58)
at rita.wordnet.jwnl.JWNL.createResourceBundle(JWNL.java:167)
at rita.wordnet.jwnl.JWNL.<clinit>(JWNL.java:51)
... 7 more
```

**Comment by dhowe** [comment]
Please try again with current download

**Comment by CyrusSUEN** [comment]
Tried following step 1 to 4 on RiTa 1.1.19
similar error happened:
```
Initializing build sequence...
Deleted old build folder
Injected log broadcaster
Detected architecture armeabi-v7a

Packaging resources with AAPT...
Compiling with ECJ...
----------
1. ERROR in /data/data/com.calsignlabs.apde/app_build/src/processing/test/riwordnet/RiWordNet.java (at line 25)
RiWordNet wordnet = new RiWordNet("wn3.1.dict/dict");
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The constructor RiWordNet(String) is undefined
----------
1 problem (1 error)
Compilation with ECJ failed
```

**Comment by dhowe** [comment]
Once we have worked out the bugs on the standard RiTa install for Android, we can think about implementing the WordNet component, perhaps with the approach used here: http://lyle.smu.edu/~tspell/jaws/index.html

**Comment by dhowe** [comment]
Also, see about removing the configuration file (file_properties.xml) and hardcoding the values in RiWordNet -- not a big deal, but would be nice to remove that file from the installation completely...

**Comment by SaraQub** [comment]
Please, do you now how to use wordnet in android studio?
I can't find any steps to follow it. 
thank you..

**Comment by dhowe** [comment]
What happens when you try to use it?
