### ISSUE TITLE
testLexicalData() fails on Windows

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#173]
java.lang.AssertionError:  expected: 'ey1|dt|' but found: 'ey1|dt'

**Comment by dhowe** [comment]
OS X is ok?

**Comment by CyrusSUEN** [comment]
> OS X is ok?

Yes. No problem on Mac.

But testRandomWordInt() can sometimes fail as well.
https://travis-ci.org/dhowe/RiTa/builds/67712181
https://travis-ci.org/dhowe/RiTa/builds/68701028

Need to investigate RiLexicon()

**Comment by CyrusSUEN** [comment]
Problem lies in line 187 of JSONLexicon.java
```java
return clean.split("\\|?\\n");
```
The value of variable 'clean' is the same on both platform but after the split() they varies.
On Windows it returns a result the same as calling ```clean.split("\\n")```

**Comment by dhowe** [comment]
try using: 
````java
return clean.split("\\|?[\\n\\r]");

**Comment by CyrusSUEN** [comment]
> return clean.split("\\|?[\\n\\r]");

Doesn't work
![3](https://cloud.githubusercontent.com/assets/2461812/9068854/6fab9d8a-3b18-11e5-9c19-cb3f06dfee64.PNG)

**Comment by dhowe** [comment]
if that doesn't work, you might try:
````java
String splitter = "\\|?" + System.getProperty("line.separator");
return clean.split(splitter);
````
or even
````java
String splitter = "\\|?\\" + System.getProperty("line.separator");
return clean.split(splitter);
````

**Comment by CyrusSUEN** [comment]
> if that doesn't work, you might try:

Oh thanks!
These two work!

**Comment by CyrusSUEN** [comment]
now it passes JUnit test on both Windows and Mac 
PR: https://github.com/dhowe/RiTa/pull/175

**Comment by dhowe** [comment]
We should be careful we are not using \\n in any other regexs

**Comment by dhowe** [comment]
just do a search for \\n  and make sure it is not getting put into any regexs

**Comment by CyrusSUEN** [comment]
Here is about 50% or 70% of the result of searching '\n' 
Please tell me which are not necessary to mention and I will finish the remaining later.

RiGrammarEditor.java
```java
  public static String jsonToString(String filename, Object parent) {
    
    String s = RiTa.loadString("myfile.json", parent);
    s = s.replaceAll("([\\r\\n]*\\s)*", ""); // remove line-break
    s = s.replaceAll("\"", "\\\\\"");       // escape all quotes
    s = "String grammar = \"" + s + "\";"; // add header & footer
    return s;
  }
```

PageLayout.java
```java
  public RiText[] layoutFromFile(PFont pf, String fileName, float leading)
  {
    String txt = RiTa.loadString(fileName, _pApplet);
    return layout(pf, txt.replaceAll("[\\r\\n]", " "), leading);
  }
```

Conjugator.java
```
  public String toString() {
    String s = "\nConjugator:\n";
    s += "  ---------------------\n";
    // s += "Coordinate = "+isCoordinate()+"\n";
    // s += "Negated = "+isNegated()+"\n";
    s += "  Passive = " + isPassive() + "\n";
    s += "  Perfect = " + isPerfect() + "\n";
    s += "  Progressive = " + isProgressive() + "\n";
    s += "  ---------------------\n";
    // s += "Category = "+getCategory()+"\n";
    // s += "Complements = "+getComplements()+"\n";
    // s += "Form = "+getForm()+"\n";
    s += "  Number = " + getNumber() + "\n";
    s += "  Person = " + getPerson() + "\n";
    s += "  Tense = " + getTense() + "\n";
    s += "  ---------------------\n";
    return s;
  }
```

line 199 of Constants.java
```
  String BN = "\n", DASH = "-", AMP = "&", EQ="=", USC = "_";
```

line 37 of LegacyGrammar.java
```
  public static final String BR = "\r";
```
line 960
```
    String IN = "  ", DQ ="\"", LB = "\n";
```
Also in LegacyGrammar.java
```java
  static boolean isLineBreak(String s)
  {
    if (s == null)
      return false;
    return (s.equals(BR) || s.equals("\n"));
  }
```

line 128 and 129 of RuleParser.java
```
      case StreamTokenizer.TT_EOL:
      result = "\n";
```

line 383 of TextNode.java
```
      String tok = node.token();      
      if (tok != null) {         
        if (tok.equals("\n"))
          tok = "\\n";
        else if (tok.equals("\r"))
          tok = "\\r";
        else if (tok.equals("\t"))
          tok = "\\t";
        else if (tok.equals("\r\n"))
          tok = "\\r\\n";
      }
```

**Comment by CyrusSUEN** [comment]
This is how p5.js deals with CRLF. (found during the search)
```js
  // normalize newline variants according to spec -> CRLF
  function normalize(s) {
    return s ? s.replace(/\r?\n/g, '\r\n') : ''
  }
```

Remaining results of searching '\n' in RiTa repo:

line 334 of js\src\rita/js
```js
  _loadStringNode: function(url, callback, linebreakChars) {

    var data = '', lb = linebreakChars || SP,
      isUrl = /.+?:\/\/.+/.test(url), me = this;

    //log("Using Node for: "+url +" isUrl="+isUrl);

    if (isUrl) {

      var httpcb = function(response) {
        response.on('data', function(chunk) {
          data += chunk;
        });
        response.on('error', function(e) {
          throw e;
        });
        response.on('end', function() {
          data = data.toString('utf-8').replace(/[\r\n]+/g, lb).trim();
          me.fireDataLoaded(url, callback, data);
        });
      };

      var req = require('http').request(url, httpcb);
      req.on('socket', function(socket) { // shouldnt be needed

        socket.setTimeout(5000); // ?
        socket.on('timeout', function() {
          req.abort();
          throw Error("[RiTa] loadString timed-out and aborted request");
        });
      });
      req.end();

    } else {

      // try with node file-system
      var rq = require('fs');
      rq.readFile(url, function(e, data) {
        if (e || !data) {
          err("[Node] Error reading file: " + url + "\n" + e);
          throw e;
        }
        data = data.toString('utf-8').replace(/[\r\n]+/g, lb).trim();
        me.fireDataLoaded(url, callback, data);
      });
    }
  },
```

line 1163 of js\src\ritext.js
```js
		txt = txt.replace(/[\r\n]/g, SP);
```

**Comment by CyrusSUEN** [comment]
> But testRandomWordInt() can sometimes fail as well.
> https://travis-ci.org/dhowe/RiTa/builds/67712181
> https://travis-ci.org/dhowe/RiTa/builds/68701028

Cannot be reproduced.

**Comment by dhowe** [comment]
What is the status of this ticket?

**Comment by CyrusSUEN** [comment]
> What is the status of this ticket?

testRandomWordInt() is a platform independent problem.

This error occasionally happens on my machine and Travis-CI 
```
    [junit] Testcase: testRandomWordInt took 0.027 sec
    [junit] 	FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit] 	at rita.support.QUnitStubs.ok(QUnitStubs.java:34)
    [junit] 	at rita.test.RiLexiconTest.testRandomWordInt(RiLexiconTest.java:250)
```
This is the affected test case:
```java
  @Test
  public void testRandomWordInt() {
    
    RiLexicon lex = new RiLexicon();

    for (int i = 0; i < 10; i++) {
      String result = lex.randomWord(5);
      String syllables = RiTa.getSyllables(result);
      int num = syllables.split(RiTa.SYLLABLE_BOUNDARY).length;
      if (num != 5)
	System.err.println("[WARN] '" + result
	    + "' has wrong syllable count 5 != " + num);
      ok(num == 5); // "5 syllableCount: "
    }
  }
```

**Comment by CyrusSUEN** [comment]
Open a new ticket for this: https://github.com/dhowe/RiTa/issues/188
Closing this one.
