### ISSUE TITLE
testRandomWordInt() occasionally fails 

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#188]
It's been logged on Travis CI:
https://travis-ci.org/dhowe/RiTa/builds/67712181
https://travis-ci.org/dhowe/RiTa/builds/68701028

And sometimes when running 'ant' command:
```
    [junit] Testcase: testRandomWordInt took 0.027 sec
    [junit]     FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit]     at rita.support.QUnitStubs.ok(QUnitStubs.java:34)
    [junit]     at rita.test.RiLexiconTest.testRandomWordInt(RiLexiconTest.java:250)
````

This is the affected test case:
```java
  @Test
  public void testRandomWordInt() {
    
    RiLexicon lex = new RiLexicon();

    for (int i = 0; i < 10; i++) {
      String result = lex.randomWord(5);
      String syllables = RiTa.getSyllables(result);
      int num = syllables.split(RiTa.SYLLABLE_BOUNDARY).length;
      if (num != 5)
	System.err.println("[WARN] '" + result
	    + "' has wrong syllable count 5 != " + num);
      ok(num == 5); // "5 syllableCount: "
    }
  }
```

I wonder if there is a way to log the error it fails on Travis CI?

**Comment by CyrusSUEN** [comment]
Tried looping that 10000000 times in JUnit: all green.
But the chance of failing is much higher when running in ant and on Travis CI.

**Comment by dhowe** [comment]
does it ever fail in local ant tests?

**Comment by CyrusSUEN** [comment]
> does it ever fail in local ant tests?

Yes. It failed twice during my local ant build.

**Comment by dhowe** [comment]
ok, so debug
