### ISSUE TITLE
Print friendlier message when WordNet not found

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/RiTa#194]
The Processing examples RandomSyns and ReplaceableWriting use WordNet dictionary. 

When the dictionary is not found prints:
```java
[INFO] RiTa.version [1.1.0]
[WARN] The font 'arial' has size=14, but fontSize of 36.0 was requested. Upscaled bitmap fonts are not likely to render well...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at rita.wordnet.jwnl.util.factory.Element.install(Element.java:35)
	at rita.wordnet.jwnl.JWNL.initialize(JWNL.java:168)
	at rita.RiWordNet.initWordNet(RiWordNet.java:2300)
	at rita.RiWordNet.<init>(RiWordNet.java:143)
	at rita.RiWordNet.<init>(RiWordNet.java:124)
	at RandomSyns.setup(RandomSyns.java:43)
	at processing.core.PApplet.handleDraw(PApplet.java:2373)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1507)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
Caused by: rita.wordnet.jwnl.JWNLException: The properties file must specify a dictionary path
	at rita.wordnet.jwnl.util.factory.AbstractValueParam.create(AbstractValueParam.java:35)
	at rita.wordnet.jwnl.dictionary.FileBackedDictionary.installStatic(FileBackedDictionary.java:122)
	... 13 more
Caused by: rita.wordnet.RiWordNetError: 
 [ERROR] Couldn't find file: /WordNet-3.1/dict/adj.exc
	at rita.wordnet.WordnetDictionaryFile.openFile(WordnetDictionaryFile.java:153)
	at rita.wordnet.jwnl.dictionary.file.AbstractDictionaryFile.open(AbstractDictionaryFile.java:67)
	at rita.wordnet.jwnl.dictionary.file.DictionaryCatalog.open(DictionaryCatalog.java:57)
	at rita.wordnet.jwnl.dictionary.file.DictionaryCatalogSet.open(DictionaryCatalogSet.java:43)
	at rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl.<init>(FileManagerImpl.java:108)
	at rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl.create(FileManagerImpl.java:137)
	at rita.wordnet.jwnl.util.factory.AbstractValueParam.create(AbstractValueParam.java:33)
	... 14 more
[WARN] Invoke error on RandomSyns.onRiTaEvent([RiTaEvent[#1424315623 type=Timer src=RiTimer#1 data-length=1]])
  java.lang.NullPointerException
    rita.RiWordNet.getRandomWord(RiWordNet.java:2436)
    rita.RiWordNet.getRandomWord(RiWordNet.java:2418)
    RandomSyns.onRiTaEvent(RandomSyns.java:58)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:497)
    rita.RiTa._invoke(RiTa.java:813)
    rita.RiTaEvent.fire(RiTaEvent.java:67)
    rita.support.RiTimer$1.run(RiTimer.java:93)
    java.util.TimerThread.mainLoop(Timer.java:555)
    java.util.TimerThread.run(Timer.java:505)

rita.RiTaException: java.lang.NullPointerException
	at rita.RiTa._invoke(RiTa.java:825)
	at rita.RiTaEvent.fire(RiTaEvent.java:67)
	at rita.support.RiTimer$1.run(RiTimer.java:93)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
	at rita.RiWordNet.getRandomWord(RiWordNet.java:2436)
	at rita.RiWordNet.getRandomWord(RiWordNet.java:2418)
	at RandomSyns.onRiTaEvent(RandomSyns.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at rita.RiTa._invoke(RiTa.java:813)
	... 4 more
```

Hopefully we can replace these with something like "WordNet 3.1 is not found...".

**Comment by dhowe** [comment]
Please verify.
![screen shot 2015-10-10 at 8 06 06 pm](https://cloud.githubusercontent.com/assets/737638/10411028/6416d8e4-6f8a-11e5-9cf6-bf7e3cd7c26d.png)

**Comment by CyrusSUEN** [comment]
verified and closing
