### ISSUE TITLE
Tests failing for 'gulp test-npm', but ok with 'gulp test'

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#344]
```
dhowe@slipper:RiTaJS$ gulp test-npm
[17:02:13] Using gulpfile ~/Documents/Projects/RiTaJS/gulpfile.js
[17:02:13] Starting 'clean'...
[17:02:13] Finished 'clean' after 11 ms
[17:02:13] Starting 'build-nolex'...
[17:02:13] Starting 'build-lex'...
[17:02:13] rita.js 150.56 kB
[17:02:14] Finished 'build-nolex' after 57 ms
[17:02:14] rita-full.js 1.64 MB
[17:02:14] Finished 'build-lex' after 48 ms
[17:02:14] Starting 'build'...
[17:02:14] Finished 'build' after 13 μs
[17:02:14] Starting 'test-npm'...
[17:02:14] Starting 'test-only'...
[INFO] Source: dist/rita.js
[17:02:14] Finished 'test-npm' after 148 ms
[INFO] Testing LibraryStructure
[INFO] Testing RiTaEvent
[INFO] Testing RiString
[INFO] RiString-tests: skipping lexicon-required tests
[INFO] Testing RiTa
[INFO] RiTa-tests: skipping lexicon-required tests
[INFO] RiTa-tests: skipping Lancaster tests
[INFO] Testing RiGrammar
[INFO] Testing RiMarkov
[INFO] Testing UrlLoading

Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 151   │ 2261       │ 3      │ 2258   │ 2385    │
└───────┴───────┴────────────┴────────┴────────┴─────────┘


Errors:

Module: RiString Test: testPos
    at Object.<anonymous> (/Users/dhowe/Documents/Projects/RiTaJS/test/RiString-tests.js:567:5)
Actual value:
[ 'nn' ]
Expected value:
[ 'nns' ]

Module: RiTa Test: testGetPosTags
    at Object.<anonymous> (/Users/dhowe/Documents/Projects/RiTaJS/test/RiTa-tests.js:735:7)
Actual value:
[ 'nn' ]
Expected value:
[ 'nns' ]

Module: RiTa Test: testGetPosTagsInline
    at Object.<anonymous> (/Users/dhowe/Documents/Projects/RiTaJS/test/RiTa-tests.js:814:7)
Actual value:
teeth/nn
Expected value:
teeth/nns
[17:02:17] Finished 'test-only' after 3.62 s

dhowe@slipper:RiTaJS$ gulp test
[17:02:43] Using gulpfile ~/Documents/Projects/RiTaJS/gulpfile.js
[17:02:43] Starting 'test'...
[17:02:43] Starting 'test-only'...
[INFO] Source: dist/rita-full.js
[INFO] Testing LibraryStructure
[INFO] Testing RiTaEvent
[INFO] Testing RiString
[INFO] Testing RiTa
[INFO] RiTa-tests: skipping Lancaster tests
[INFO] Testing RiGrammar
[INFO] Testing RiMarkov
[INFO] Testing UrlLoading
[INFO] Testing RiLexicon

Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 186   │ 5555       │ 0      │ 5555   │ 6410    │
└───────┴───────┴────────────┴────────┴────────┴─────────┘
[17:02:50] Finished 'test-only' after 7.64 s
```

**Comment by dhowe** [comment]
fixed
