### ISSUE TITLE
Examples fail in android mode/standalone app

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#389]
Analysis and RandomRhymes work well in Android, but the following examples fail:

HaikuGrammar, Kafgenstein, KWICmodel
![image](https://cloud.githubusercontent.com/assets/3056154/20873338/7182d5a2-bae1-11e6-8c45-b982fb8d4555.png)

ReplaceableWriting

> FATAL EXCEPTION: Animation Thread
Process: processing.test.replaceablewriting, PID: 25091
rita.wordnet.RiWordNetError:
 [ERROR] Unable to find WordNet at '/WordNet-3.1' -- have you downloaded & installed it?
    at rita.RiWordNet.<init>(Unknown Source)
    at rita.RiWordNet.<init>(Unknown Source)
    at processing.test.replaceablewriting.ReplaceableWriting.setup(ReplaceableWriting.java:38)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:818)
Caused by: rita.wordnet.jwnl.JWNLException: Unable to install rita.wordnet.jwnl.dictionary.FileBackedDictionary
    at rita.wordnet.jwnl.util.factory.Element.install(Unknown Source)
    at rita.wordnet.jwnl.JWNL.initialize(Unknown Source)
    at rita.RiWordNet.initWordNet(Unknown Source)
    ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    ... 10 more
Caused by: rita.wordnet.jwnl.JWNLException: The properties file must specify a dictionary path
    at rita.wordnet.jwnl.util.factory.AbstractValueParam.create(Unknown Source)
    at rita.wordnet.jwnl.dictionary.FileBackedDictionary.installStatic(Unknown Source)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:324)
    at java.lang.Class.forName(Class.java:285)
    ... 13 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl" on path: DexPathList[[zip file "/data/app/processing.test.replaceablewriting-1/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.replaceablewriting-1/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    ... 16 more
    Suppressed: java.lang.NoClassDefFoundError: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        ... 18 more
    Suppressed: java.lang.ClassNotFoundException: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 17 more
    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by dhowe** [comment]
So, each of those require loading of an external file. I assume this must be allowed in processing/android, so we need to figure out how. In worst case, where we can't figure it out, we will need to include the content of the files in the source (but this shouldn't be needed).

**Comment by cqx931** [comment]
Two findings at this point:
1.The failing files for HaikuGrammar, Kafgenstein, KWICmodel are caused by the current folder structure
<img width="566" alt="screen shot 2016-12-07 at 1 25 15 pm" src="https://cloud.githubusercontent.com/assets/3056154/20955960/f1b9d990-bc81-11e6-9683-0389a147ab4b.png">
Now the files are out of the sketch folder and when android build the whole sketch it will just look into the sketch folder and corresponding libraries.
If I move the file into the data folder within the sketch, these three examples work.

Shall we consider restructuring the example folders accordingly?

2. Mouseclicked
https://github.com/processing/processing/issues/1467
According to the above issue, click event is not fired on android.
Now Kafgenstein and KWICmodel are using mouseClick(), we can replace them with mouseReleased(), then they will work in android as well.

**Comment by dhowe** [comment]
1. yes, agreed
2. excellent, please make the change

**Comment by cqx931** [comment]
please check https://github.com/dhowe/RiTa/pull/390

**Comment by dhowe** [comment]
looks good, but we need to do a build, then run the examples on each of the platforms, to make sure we haven't caused any problem

**Comment by cqx931** [comment]
I don't see why this would influence the build. All the changes are only made within the examples folder in RiTa(Java), so this will only influence the following test cases:
Java

- In Processing

- As a standalone Java program (jar)

- In Processing for android

- As a standalone Android app (jar)

**Comment by dhowe** [comment]
@cqx931  status?

**Comment by cqx931** [comment]
The issue is solved with the commit above.
I haven't changed anything in RiTa itself, so I think there is no need to do a build(see my last comment), The examples work on Android after #390

**Comment by dhowe** [comment]
We will test it again for v1.6 release
