### ISSUE TITLE
Test Eclipse dev setup for version 1.2

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTa#406]
https://github.com/dhowe/RiTa/blob/master/README.md

**Comment by cqx931** [comment]
Got file name too long error when I try to clone the depository to eclipse (Step 6)
```
org.eclipse.jgit.api.errors.JGitInternalException: File name too long
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:138)
	at org.eclipse.egit.core.op.CloneOperation.run(CloneOperation.java:156)
	at org.eclipse.egit.ui.internal.clone.AbstractGitCloneWizard.executeCloneOperation(AbstractGitCloneWizard.java:445)
	at org.eclipse.egit.ui.internal.clone.AbstractGitCloneWizard.access$2(AbstractGitCloneWizard.java:438)
	at org.eclipse.egit.ui.internal.clone.AbstractGitCloneWizard$5.run(AbstractGitCloneWizard.java:399)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.io.IOException: File name too long
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1162)
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:450)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:396)
	at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:251)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
	... 5 more

```

**Comment by dhowe** [comment]
for what file?

**Comment by cqx931** [comment]
This is all I got, can't find the exact file name from the log
<img width="517" alt="2017-04-25 1 36 48" src="https://cloud.githubusercontent.com/assets/3056154/25370296/4ccaa380-29bc-11e7-96bf-b5eaca2d011f.png">

**Comment by dhowe** [comment]
I'm looking at eclipse neon now

**Comment by dhowe** [comment]
I get the same error:

![image](https://cloud.githubusercontent.com/assets/737638/26294010/620f6ebe-3ef3-11e7-85a0-b1152ebb391c.png)

**Comment by dhowe** [comment]
all good
