### ISSUE TITLE
Remove #using-riwordnet-with-processing-on-android-android-support-coming-soon?

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#424]
https://github.com/dhowe/RiTa/blob/master/README.WordNet.md#using-riwordnet-with-processing-on-android-android-support-coming-soon
RiWordNet is currently not working in Processing android mode.
If I put the WordNet folder into data folder, it works well in java but I got the following error messages if I do the same thing in android mode:
```
[ERROR] Unable to find WordNet at 'WordNet-3.1' -- have you downloaded & installed it?
	at rita.RiWordNet.<init>(Unknown Source)
	at rita.RiWordNet.<init>(Unknown Source)
	at processing.test.replaceablewriting.ReplaceableWriting.setup(ReplaceableWriting.java:38)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
Caused by: rita.wordnet.jwnl.JWNLException: Unable to install rita.wordnet.jwnl.dictionary.FileBackedDictionary
	at rita.wordnet.jwnl.util.factory.Element.install(Unknown Source)
	at rita.wordnet.jwnl.JWNL.initialize(Unknown Source)
	at rita.RiWordNet.initWordNet(Unknown Source)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	... 10 more
Caused by: rita.wordnet.jwnl.JWNLException: The properties file must specify a dictionary path
	at rita.wordnet.jwnl.util.factory.AbstractValueParam.create(Unknown Source)
	at rita.wordnet.jwnl.dictionary.FileBackedDictionary.installStatic(Unknown Source)
	... 11 more
Caused by: java.lang.ClassNotFoundException: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	... 13 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl" on path: DexPathList[[zip file "/data/app/processing.test.replaceablewriting-1/base.apk"],nativeLibraryDirectories=[/data/app/processing.test.replaceablewriting-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 16 more
	Suppressed: java.lang.NoClassDefFoundError: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
		at dalvik.system.DexFile.defineClassNative(Native Method)
		at dalvik.system.DexFile.defineClass(DexFile.java:226)
		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
		... 18 more
	Suppressed: java.lang.ClassNotFoundException: rita.wordnet.jwnl.dictionary.file_manager.FileManagerImpl
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 17 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

**Comment by dhowe** [comment]
Once 1.6 is published, lets discuss RiWordNet on Android (in Processing and outside). This issue has been around for a long time and it should not be hard to solve.

**Comment by thnewlands** [comment]
Any updates on RiWordNet for android?

**Comment by dhowe** [comment]
on hold for now (need an android person to take a look)
