### ISSUE TITLE
Error messages in rita.js

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#436]
1. Error when LTS is first initialized
To recreate, run
```
gulp build
gulp test.quick
```
```
Module: RiString Test: testAnalyze
Died on test #1     at global.test.QUnit.test (/Users/cqx931/RiTaJS/node_modules/qunit/lib/child.js:146:21)
    at runtests (/Users/cqx931/RiTaJS/test/RiString-tests.js:59:3)
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiString-tests.js:1456:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3): Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.init (/Users/cqx931/RiTaJS/dist/rita.js:1600:44)
    at Object.<anonymous> (/Users/cqx931/RiTaJS/dist/rita.js:12:19)
    at Object._letterToSound (/Users/cqx931/RiTaJS/dist/rita.js:1553:18)
    at Object._getRawPhones (/Users/cqx931/RiTaJS/dist/rita.js:1377:21)
    at Object.analyze (/Users/cqx931/RiTaJS/dist/rita.js:2646:27)
    at Object.<anonymous> (/Users/cqx931/RiTaJS/test/RiString-tests.js:63:32)
```
2.RiLexicon
Go to RiLexicon-tests.html and change `rita-full.js` to `rita.js`

```
at runtests (file:///Users/cqx931/RiTaJS/test/RiLexicon-tests.js:37:3): Cannot read property 'length' of undefined
Source: 	
TypeError: Cannot read property 'length' of undefined
    at Object.size (file:///Users/cqx931/RiTaJS/dist/rita.js:1264:21)
    at Object.<anonymous> (file:///Users/cqx931/RiTaJS/test/RiLexicon-tests.js:39:12)

```

**Comment by cqx931** [comment]
Two remaining errors after update:
![image](https://cloud.githubusercontent.com/assets/3056154/26247533/e5d3a208-3cd0-11e7-94d9-a8ea273d85dc.png)
![image](https://cloud.githubusercontent.com/assets/3056154/26247536/e838785c-3cd0-11e7-8cf0-efbb6666cab0.png)

**Comment by cqx931** [comment]
fixed
