### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by cqx931** [dhowe/RiTa#520]
```
cd node_modules/rita && npm install && npm test

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm notice created a lockfile as package-lock.json. You should commit this file.
added 431 packages in 12.23s

> rita@1.3.84 test /Users/cqx931/ritaTest/node_modules/rita/node_modules/rita
> gulp test-npm

[16:05:44] Using gulpfile ~/ritaTest/node_modules/rita/node_modules/rita/gulpfile.js
[16:05:44] Starting 'clean'...
[16:05:44] Finished 'clean' after 3.97 ms
[16:05:44] Starting 'build-lex'...
[16:05:44] Starting 'build-1000-lex'...
[16:05:44] Starting 'build-nolex'...
[16:05:44] Finished 'build-lex' after 24 ms
[16:05:44] Finished 'build-nolex' after 11 ms
[16:05:44] Finished 'build-1000-lex' after 14 ms
[16:05:44] Starting 'build'...
[16:05:44] Finished 'build' after 33 μs
[16:05:44] Starting 'test-npm'...
[16:05:44] Starting 'test-only'...
[INFO] Source: lib/rita.js
[16:05:44] Finished 'test-npm' after 120 ms
[INFO] Testing LibraryStructure
[INFO] Testing RiString
[INFO] Testing RiTa
[INFO] Testing RiGrammar
[INFO] Testing RiMarkov
[INFO] Testing UrlLoading
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14) message: 'connect ECONNREFUSED 127.0.0.1:80' }
{ files: 0,
  assertions: 0,
  failed: 0,
  passed: 0,
  runtime: 0,
  tests: 151,
  coverage: 
   { files: 0,
     statements: { covered: 0, total: 0 },
     branches: { covered: 0, total: 0 },
     functions: { covered: 0, total: 0 },
     lines: { covered: 0, total: 0 } } }
npm ERR! Test failed.  See above for more details.
chenqianxun-Sally-Chen:rita cqx931$ 

```

**Comment by cqx931** [comment]
no more valid
