### ISSUE TITLE
Error In untokenization

### ISSUE THREAD

**Issue by create-account** [dhowe/RiTa#543]
Here is the error I got for RiTa JS, when I tried to untokenize a tokenized array:
```
  C:\Users\ron\Documents\rita-js-sample\node_modules\rita\lib\rita.js:33
witness:["w-ih1-t n-ah-s","nn vb"],witnessed:["w-ih1-t n-ah-s-t","vbn vbd"],witnessing:["w-ih1-t n-ah s-ih-ng","vbg"],wittily:["w-ih1 t-ah l-iy","rb"],wittingly:["w-ih1 t-ih-ng l-iy","rb"],witty:["w-ih1 t-iy","jj"],wizard:["w-ih1 z-er-d","nn"],wobble:["w-aa1 b-ah-l","vb nn"],wobbled:["w-aa1 b-ah-l-d","vbd vbn"],wobbling:["w-aa1 b-ah-l ih-ng","vbg"],wobbly:["w-aa1 b-ah-l iy","jj"],woe:["w-ow1","nn"],woeful:["w-ow1 f-ah-l","jj"],woefully:["w-ow1 f-ah l-iy","rb"],woke:["w-ow1-k","vbd"],woken:["w-ow1 k-ah-n","vbn"],wolf:["w-uh1-l-f","nn"],woman:["w-uh1 m-ah-n","nn"],women:["w-ih1 m-eh-n","nns"],womanhood:["w-uh1 m-ah-n hh-uh-d","nn"],womanize:["w-uh1-m-ah-n-ay-z","vb"],womanizing:["w-uh1 m-ah n-ay z-ih-ng","vbg"],womb:["w-uw1-m","nn"],won:["w-ah1-n","vbd nn vbn"],wonder:["w-ah1-n d-er","nn vbp jj vb"],wondered:["w-ah1-n d-er-d","vbd vbn"],wonderful:["w-ah1-n d-er f-ah-l","jj"],wonderfully:["w-ah1-n d-er f-ah l-iy","rb"],wonderfulness:["w-ah1-n

TypeError: Cannot read property 'charAt' of undefined
    at Object.untokenize (C:\Users\ron\Documents\rita-js-sample\node_modules\rita\lib\rita.js:33:13605)
    at Object.<anonymous> (C:\Users\ron\Documents\rita-js-sample\index.js:140:14)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
```

The string I tokenized was:
`The correct method in philosophy would really be the following: to say nothing except what can be said, i.e. propositions of natural science--i.e. something that has nothing to do with philosophy -- and then, whenever someone else wanted to say something metaphysical, to demonstrate to him that he had failed to give a meaning to certain signs in his propositions. Although it would not be satisfying to the other person--he would not have the feeling that we were teaching him philosophy--this method would be the only strictly correct one.`

**Comment by dhowe** [comment]
I can't recreate the error above. I created the following simple test program:

```
var RiTa = require('./dist/rita.js');
var input = "The correct method in philosophy would really be the following: to say nothing except what can be said, i.e. propositions of natural science--i.e. something that has nothing to do with philosophy -- and then, whenever someone else wanted to say something metaphysical, to demonstrate to him that he had failed to give a meaning to certain signs in his propositions. Although it would not be satisfying to the other person--he would not have the feeling that we were teaching him philosophy--this method would be the only strictly correct one.";
var tokens = ["The","correct","method","in","philosophy","would","really","be","the","following",":","to","say","nothing","except","what","can","be","said",",","i.e.","propositions","of","natural","science","--","i.e.","something","that","has","nothing","to","do","with","philosophy","--","and","then",",","whenever","someone","else","wanted","to","say","something","metaphysical",",","to","demonstrate","to","him","that","he","had","failed","to","give","a","meaning","to","certain","signs","in","his","propositions",".","Although","it","would","not","be","satisfying","to","the","other","person","--","he","would","not","have","the","feeling","that","we","were","teaching","him","philosophy","--","this","method","would","be","the","only","strictly","correct","one","."];
var tokens = RiTa.tokenize(input);
var output = RiTa.untokenize(tokens);
console.log(JSON.stringify(tokens));
console.log(JSON.stringify(output));
```

And get the output:

```
["The","correct","method","in","philosophy","would","really","be","the","following",":","to","say","nothing","except","what","can","be","said",",","i",".","e",".","propositions","of","natural","science","--","i",".","e",".","something","that","has","nothing","to","do","with","philosophy","--","and","then",",","whenever","someone","else","wanted","to","say","something","metaphysical",",","to","demonstrate","to","him","that","he","had","failed","to","give","a","meaning","to","certain","signs","in","his","propositions",".","Although","it","would","not","be","satisfying","to","the","other","person","--","he","would","not","have","the","feeling","that","we","were","teaching","him","philosophy","--","this","method","would","be","the","only","strictly","correct","one","."]
"The correct method in philosophy would really be the following: to say nothing except what can be said, i. e. propositions of natural science -- i. e. something that has nothing to do with philosophy -- and then, whenever someone else wanted to say something metaphysical, to demonstrate to him that he had failed to give a meaning to certain signs in his propositions. Although it would not be satisfying to the other person -- he would not have the feeling that we were teaching him philosophy -- this method would be the only strictly correct one."
```

There are some minor space issues, but no error like you describe. Can you please include an [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by create-account** [comment]
I am sorry, the issue was with my code. I replaced the tokens with the synonyms and used untokenize() without noticing an undefined token in the array.
